/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    A: typeof import('./src/components/base/a.vue')['default']
    AlaColumn: typeof import('./src/components/cps/column/ala-column.vue')['default']
    AlaEmpty: typeof import('./src/components/cps/empty/ala-empty.vue')['default']
    AlaImage: typeof import('./src/components/cps/image/ala-image.vue')['default']
    AlaImg: typeof import('./src/components/cps/image/ala-img.vue')['default']
    AlaLink: typeof import('./src/components/cps/link/ala-link.vue')['default']
    Column: typeof import('./src/components/cps/column/index.vue')['default']
    ComponentTemplete: typeof import('./src/components/cps/component-templete/index.vue')['default']
    ConfigFiles: typeof import('./src/components/cps/config/config-files.vue')['default']
    ConfigImput: typeof import('./src/c./src/components/cps/config/config-textarea.vue]
    ConfigInput: typeof import('./src/components/cps/config/config-input.vue')['default']
    ConfigTextarea: typeof import('./src/components/cps/config/config-textarea.vue')['default']
    ConfigViewport: typeof import('./src/components/cps/config/config-viewport.vue')['default']
    copy: typeof import('./src/components/editor/editor-config-block copy.vue')['default']
    EditorBlock: typeof import('./src/components/editor/editor-block.vue')['default']
    EditorBlockDrag: typeof import('./src/components/editor/editor-block-drag.vue')['default']
    EditorConfig: typeof import('./src/components/editor/editor-config.vue')['default']
    EditorConfigBlock: typeof import('./src/components/editor/editor-config-block.vue')['default']
    EditorConfigPage: typeof import('./src/components/editor/editor-config-page.vue')['default']
    EditorConfigRender: typeof import('./src/components/editor/editor-config-render.vue')['default']
    EditorHeader: typeof import('./src/components/editor/editor-header.vue')['default']
    EditorRender: typeof import('./src/components/editor/editor-render.vue')['default']
    EditorRenderDrag: typeof import('./src/components/editor/editor-render-drag.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Empty: typeof import('./src/components/cps/empty/index.vue')['default']
    HelloWorld: typeof imp./ src / components / cps / image / ala - image.vue')['default ']
    Image: typeof import(./src/components / cps / link / ala - link.vueue')['default ']
    Link: typeof import('./src/components/cps/link/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VIcon: typeof import('./src/components/base/v-icon.vue')['default']
    VIconTooltip: typeof import('./src/components/base/v-icon-tooltip.vue')['default']
    VSelect: typeof import('./src/components/base/v-select.vue')['default']
    VUpload: typeof import('./src/components/base/v-upload.vue')['default']
  }
}
